name = "GoGameGraphs"
uuid = "56c941c6-2185-42eb-b028-2000e1fdc468"
authors = ["Gunnar Farnebäck <gunnar@lysator.liu.se>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
Combinatorics = "0.7, 1"
Requires = "0.5, 1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
